### ISSUE TITLE
Add event is not working in admin

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#10]
Try to create and save an event here

http://mezzanine.kartoza.com/en/admin/mezzanine_agenda/event/

**Comment by meomancer** [comment]
@timlinux 
it seems that DisplayableAdmin break it
when submit, it says that : `Forbidden (CSRF token missing or incorrect.): /id/admin/mezzanine_agenda/event/add/`

although it already has csrf token in form

**Comment by meomancer** [comment]
helo @timlinux 
it seems that the problem is from 
`RICHTEXT_WIDGET_CLASS = "mdown.forms.WmdWidget"`

i tried to remove it, and it work fine (mezzanine use tinymce as default) although there is error jquery is not found

then i tried again use mdown.forms.WmdWidget but add middle javascript to add 

```
$.ajaxSetup({
    beforeSend: function (xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
```

it is working now, posts to backend, but got error which is "invalid literal for int() with base 10: '<!DOCTYPE html>    <html lang="id" >  <head>  <title>Tambahkan Event'

going to look into it

**Comment by timlinux** [comment]
Ok Thanks. Using the MD editor is not critical, so feel free to ditch it and fall back to tinymce if that is a quicker fix.

**Comment by gubuntu** [comment]
thanks @meomancer, seems to be working :+1:
