### ISSUE TITLE
staff users cannot log in to admin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#144]
I added Admire as a staff user but he cannot login to admin to work on a blog post. 'You don't have permission to access the admin for this site'.

Surely staff should be able to log in or has another policy been implemented?

I don't think superuser status should be required nor that everyone should have superuser status. 

cc @timlinux

**Comment by timlinux** [comment]
No he should be able to log in and blog if he has a blog account. I will check.

**Comment by timlinux** [comment]
I just want to bump this again - its a pain seeing a bunch of unpublished articles - they should be listed in admin but not in the front end.

**Comment by meomancer** [comment]
please review
@timlinux
unpublished will be shown on frontend, but just for admin user
if it is non staff, unpublished will be hidden from frontend

**Comment by gubuntu** [comment]
@meomancer that relates to #147. Can you check this OP and fix or close?

**Comment by timlinux** [comment]
Ok thanks @meomancer

**Comment by boney-bun** [comment]
i've tried the `test` user (pass: `test`).
I've unticked the `Superuser status`.
Also, i clicked on **kartoza.com** on `Sites Permission` column as suggested in https://groups.google.com/forum/#!topic/mezzanine-users/jfaBdJ1UcrU
We don't need to be a superuser in order to login into admin page, just the *staff status*.
Make sure that we select **kartoza.com** on `Sites Permission` column.

i think we could close this issue.

**Comment by gubuntu** [comment]
not applicable to ERPNext
