### ISSUE TITLE
can't add product image without saving first

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#152]
you can add an image to a product but then have to save before adding another one.

you should be able to continue adding images before saving.

**Comment by meomancer** [comment]
it is already fixed

**Comment by meomancer** [comment]
found the bug but still haven't found the fix
The error is because when creating new slide, the image button is calling wrong id to filebrowser.

First image: id-slide-set-0-file
![screenshot from 2017-01-03 15 38 16](https://cloud.githubusercontent.com/assets/4530905/21602941/e3cb8cd4-d1cb-11e6-8973-ab67ce672734.png)

Second image: id-slide-set-__PREFIX__-file (strange)
![screenshot from 2017-01-03 15 38 19](https://cloud.githubusercontent.com/assets/4530905/21602942/e3cda80c-d1cb-11e6-912a-8942b2914645.png)
![screenshot from 2017-01-03 15 38 20](https://cloud.githubusercontent.com/assets/4530905/21602943/e3d04706-d1cb-11e6-9c37-9597ca464dfe.png)

Althoug it's div generate correct id
![screenshot from 2017-01-03 15 38 32](https://cloud.githubusercontent.com/assets/4530905/21602944/e3d27b16-d1cb-11e6-9db5-94700b48d24c.png)
![screenshot from 2017-01-03 15 38 51](https://cloud.githubusercontent.com/assets/4530905/21602945/e3d7ae24-d1cb-11e6-914b-3c9fb39be8fa.png)
