### ISSUE TITLE
product number in stock should only increment on order confirmation

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#162]
atm it increments on order placement.

**Comment by timlinux** [comment]
Is this right? It might lead to oversubscription of places in the course. Assuming Petra will lease with order make in one working day I think we can commit the place and or cancel the order if it is not paid.

**Comment by meomancer** [comment]
@gubuntu i think this behaviour is correct
because if we make it on order confirmation, and we have 1 stock, but 2 people make order, when they pay it, there is just 1 stock

i think the system of order like booking, it takes stock temporary. maybe we could make expire for order and cancel it automatically if it isn't paid in expire time? and when cancel, the stock is back
