### ISSUE TITLE
fix order business logic and reports

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#164]
- [x] add Kartoza logo to order e.g. http://kartoza.com/en/shop/invoice/4/
- [x] Add 'Tax Invoice' to the above order/invoice template. 
- [x] phone numbers should be text fields or formatted with leading 0 
- [x] add supplier details to the order (all Kartoza company details incl VAT no.)
- [ ] fix the order view / model (http://kartoza.com/en/admin/shop/order/4/) because it is incorrect and should match the 'invoice' in the link above. I think it's a tax implementation issue - it should be calculating VAT on the discounted amount. 
- [x] Figure out what Unprocessed/Processed does in Order admin - or is it just a boolean flag?

**Comment by meomancer** [comment]
@gubuntu 
4 - where should i put supplier detail?
6 - unprocessed/processed is just boolean flag

**Comment by gubuntu** [comment]
Where you've put them so far is OK, just add the VAT no.

**Comment by meomancer** [comment]
5 - it is hard to manipulate it @gubuntu unless from library itself
the way we are do now is manipulate date in post-processing after receive from model. 
Which is Item total is include vat, and we manipulate when creating invoice to decrease item total by tax

> item total = item total - tax
> order total = item total + tax

but on original catridge, tax is added when saved to model
https://github.com/stephenmcd/cartridge/blob/master/cartridge/shop/models.py#L494

For this, we need to change it from library because library handles product that not included tax from the beginning

**Comment by gubuntu** [comment]
I guess as long as it appears correctly on the generated invoice it's not a trainsmash if it's wrong in the model / admin for now. But I feel it should handle this correctly since it's a standard, common requirement so again, could you add a ticket upstream to fix this?
