### ISSUE TITLE
need to create two product variations before any appear

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#178]
I tried to add a product variation for Advanced GIS with FOSS yesterday. After creating one, it didn't appear on the product admin page. But after creating another one, both variations appeared. 

Expected behaviour: After creating one variation, it should appear on the product admin page.

**Comment by meomancer** [comment]
@gubuntu 

i think we have to understand how the variant works first.
After analyzing it found the variant works:
**1. when we create product, there will be current variant (default). it doesn't has variant options (venue, date)**
_sku is 45_
![selection_001](https://cloud.githubusercontent.com/assets/4530905/21040426/6d7efca4-be17-11e6-99ea-5335f448b319.png)

**2. If we create new varient, the default variant (that doesn't has options) is deleted and replaced by new variant.** The code is [here](https://github.com/stephenmcd/cartridge/blob/master/cartridge/shop/managers.py#L147). I think this is the logic implemented in the first place.
_create new variant_
![selection_002](https://cloud.githubusercontent.com/assets/4530905/21040447/91443eec-be17-11e6-8b10-63e27e18b670.png)

_now sku is 46, 45 is deleted (checked on db). It doesn't show minititle to tell the variant options,_
_because there is js that hide minititle if product just has 1 variant_
![selection_003](https://cloud.githubusercontent.com/assets/4530905/21040456/a65c4b94-be17-11e6-8cc8-72464be82a37.png)

**3. After we create the other variant, it will show mini title that tell these variant**
![selection_005](https://cloud.githubusercontent.com/assets/4530905/21040594/883a5cea-be18-11e6-99df-adb838317762.png)

**note**:
it is not new one didn't appear on product admin when create one variant. It is because it replace the empty options one that make it doesn't show up. And why when we create the second one, it is like appears (show mini title that shows variant)? because there is javascript that hide this title when we just has 1 variant.

I'm not sure it is necessary, but i made [PR](https://github.com/kartoza/docker-mezzanine/pull/180) to show minititle that will prevent confusion when we create new variant

**Comment by gubuntu** [comment]
So if you have populated the first variant and then add another one, the first one will be deleted and lost? That doesn't seem useful. 

showing the minititle for first variant makes sense...something to push upstream?
