### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by christodewit** [kartoza/docker-mezzanine#243]
# Problem

Not receiving email notifications of new course applicants.

# Solution

This used to work, make it work again. Postfix issue?

**Comment by boney-bun** [comment]
The postfix is running.

It seems there's an error on the DNS server as I found this error in the log:
```
Apr 23 04:27:12 postfix postfix/smtp[239]: 9C9DF599: to=<simon.nox186@mail.com>, relay=mx01.mail.com[74.208.5.22]:25, delay=407691, delays=407690/0.01/0.78/0, dsn=4.0.0, status=deferred (host mx01.mail.com[74.208.5.22] refused to talk to me: 554-mail.com (mxgmxus006) Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record. 554 For explanation visit http://postmaster.gmx.com/en/error-messages?ip=78.46.247.108&c=rdns)
```
The mail service encountered error starting from April 22, 2018 20:17

**Comment by petrapaton** [comment]
Thanks @boney-bun I think we are loosing business!

**Comment by boney-bun** [comment]
@petrapaton Could we send a private message to the client as we know their email on the error log?

**Comment by gubuntu** [comment]
@boney-bun it is working now, recipients must check their spam. 

What did you do to make it work or was it working all along? Deploy any fixes in code or orchestration asap and close

**Comment by boney-bun** [comment]
@gubuntu yes, it is working now.
there are two causes of the problem:
- previously we only provided *banking* email account on the bcc field in the admin page. 
   I added *info* account, but the *info* doesn't get sent by the django admin module. 
   i will need to figure out why the second specified email in the bcc field doesn't receive the email.
   I think there's a bug on that.
   for now, the email order in the bcc field is: *info*, *banking*. 

- there was a problem, (not sure which one) whether in cloudflare or DNS server, that caused the smtp failed to send the email. in the best case, the smtp will be "self healed" when the problem in these two servers goes away. but, there was a case where i need to restart the smtp container in order to make it normal.

@gubuntu perhaps we could close this issue and make another issue regarding the bcc field.
or, let's keep this issue open and will close it if the bug resolved.
which one do you prefer?

**Comment by gubuntu** [comment]
@boney-bun please close if mail is indeed being sent (check again) and create another issue for the bcc problem
