### ISSUE TITLE
We need to deploy django-wms

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#75]
@ismailsunni write this some time ago:

https://github.com/kartoza/django-wms-client

I'd like us to use that rather than the static page for http://maps.kartoza.com

Please deploy it and point to the same maps we have in the gallery. Ask @ismailsunni for help if you need to understand what it does.

**Comment by timlinux** [comment]
Note we only need the app itself : 

https://github.com/kartoza/django-wms-client/tree/develop/django_project/wms_client

Maybe we should refactor that repo to get rid of the docker stuff.....

**Comment by meomancer** [comment]
hello @timlinux 
i already made simple version of this to be as library
https://github.com/meomancer/django-wms-client/tree/mezzanine

already tried it and intergrated in mezzanine nicely

my purpose is:
- move to mezzanine-wms-client? because admin.py will be changed based on mezzanine admin?
- if yes, i think i will update it because i want to make description of map page can be customized on admin (or should we make page type? and we could assign wms config for specific page, so user can has 2 or more page that contains it's map?)

@ismailsunni 
i got bug that when config, and we put north, etc to empty, it will be broken if our url is not correct

**Comment by timlinux** [comment]
@meomancer yes being able to embed the WMS in a page would be really nice. +1 from me to 'mezzaninify' it!
