### ISSUE TITLE
When saving a new record in mezzanine people a duplicate entry is made

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-mezzanine#82]
See screencast below. A duplicate entry is made whenever you create a new person.

![globe](https://cloud.githubusercontent.com/assets/178003/18195586/9fb97e7e-70ec-11e6-9e9d-dc964e86fc3a.gif)

**Comment by meomancer** [comment]
@timlinux 
i think the website is not updated
https://github.com/kartoza/docker-mezzanine/pull/53

here is the js that break : http://mezzanine.kartoza.com/static/mezzanine/js/admin/keywords_field.js
you could see it is different with : /home/timlinux/mezzanine.kartoza.com/deployment/static/mezzanine/js/admin$ cat keywords_field.js 

and it fixed by 
https://github.com/kartoza/docker-mezzanine/pull/53
